plugins {
  id("awesome.androidlib.plugin")
}

dependencies {
    
    implementation(project(":layer_1:module_1_64"))
    implementation(project(":layer_1:module_1_86"))
    implementation(project(":layer_1:module_1_89"))
    implementation(project(":layer_1:module_1_58"))
    implementation(project(":layer_1:module_1_42"))
    implementation(project(":layer_1:module_1_52"))
    implementation(project(":layer_1:module_1_44"))
    implementation(project(":layer_1:module_1_51"))
    implementation(project(":layer_1:module_1_46"))
    implementation(project(":layer_1:module_1_81"))
    implementation(project(":layer_1:module_1_63"))
    implementation(project(":layer_1:module_1_54"))
    implementation(project(":layer_1:module_1_83"))
    implementation(project(":layer_1:module_1_79"))
    implementation(project(":layer_1:module_1_74"))
    implementation(project(":layer_1:module_1_66"))
    implementation(project(":layer_1:module_1_90"))
    implementation(project(":layer_1:module_1_72"))
    implementation(project(":layer_1:module_1_53"))
    implementation(project(":layer_1:module_1_78"))
    implementation(project(":layer_1:module_1_68"))
    implementation(project(":layer_1:module_1_43"))
    implementation(project(":layer_1:module_1_80"))
    implementation(project(":layer_1:module_1_45"))
    implementation(project(":layer_1:module_1_88"))
    implementation(project(":layer_1:module_1_84"))
    implementation(project(":layer_1:module_1_71"))
    implementation(project(":layer_1:module_1_62"))
    implementation(project(":layer_1:module_1_38"))
    implementation(project(":layer_1:module_1_65"))
    implementation(project(":layer_1:module_1_69"))
    implementation(project(":layer_1:module_1_59"))
    implementation(project(":layer_1:module_1_50"))
    implementation(project(":layer_1:module_1_56"))
    implementation(project(":layer_1:module_1_61"))
    implementation(project(":layer_1:module_1_67"))
    implementation(project(":layer_1:module_1_82"))
    implementation(project(":layer_1:module_1_85"))
}
        